version: '2'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"

  # frontend:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - BACKEND_URL: http://server:5000
